# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20161120_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_id', models.CharField(max_length=20, verbose_name='String id')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published')),
                ('is_active', models.BooleanField(default=True, verbose_name='comment status')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comments',
                'verbose_name': 'comment',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_id', models.CharField(max_length=20, verbose_name='String id')),
                ('issue', models.PositiveSmallIntegerField(choices=[(1, 'Spam'), (2, 'Hate speech'), (3, 'Sexually explicit'), (4, 'Harassment or bullying'), (5, 'Violent or threatening')], help_text='What is wrong with this comment?', verbose_name='report')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comment reports',
                'verbose_name': 'comment report',
            },
        ),
    ]
