# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161119_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Animals'), (2, 'Art & Design'), (3, 'Comedy'), (4, 'Education'), (5, 'Entertainment'), (6, 'Fashion'), (7, 'Food'), (8, 'Gaming'), (9, 'Movies'), (10, 'Music'), (11, 'News'), (12, 'Photography'), (13, 'Sports'), (14, 'Vlog')], null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_time',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='thumbnail time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='views'),
        ),
    ]
